export const CATEGORIES = [
  { id: 'cro-growth', name: 'CRO & Growth', icon: 'TrendingUp', color: '#F54E00', slug: 'cro-growth', count: 24 },
  { id: 'devops', name: 'DevOps & Deploy', icon: 'Server', color: '#5B8DEF', slug: 'devops', count: 18 },
  { id: 'content', name: 'Content & Copy', icon: 'PenTool', color: '#A855F7', slug: 'content', count: 15 },
  { id: 'analytics', name: 'Analytics & Data', icon: 'BarChart2', color: '#FBBF24', slug: 'analytics', count: 21 },
  { id: 'design', name: 'Design & UI', icon: 'Palette', color: '#EC4899', slug: 'design', count: 12 },
  { id: 'product', name: 'Product & Research', icon: 'Lightbulb', color: '#F97316', slug: 'product', count: 9 },
  { id: 'finance', name: 'Finance & Ops', icon: 'DollarSign', color: '#FBBF24', slug: 'finance', count: 7 },
  { id: 'starter-kits', name: 'Starter Kits', icon: 'Package', color: '#F54E00', slug: 'starter-kits', count: 5 },
];

export const MOCK_ITEMS = [
  // AGENTS - CRO & Growth
  {
    id: 'item_1',
    slug: 'ga4-conversion-watchdog',
    title: 'GA4 Conversion Watchdog',
    shortDescription: 'Monitors GA4 conversion rates and alerts on drops via Slack.',
    description: 'A powerful agent that continuously monitors your Google Analytics 4 conversion rates and sends real-time alerts to Slack whenever conversion rates drop below your thresholds. Includes configurable sensitivity, daily digests, and anomaly detection using statistical analysis.',
    type: 'agent',
    category: 'cro-growth',
    tags: ['ga4', 'conversions', 'slack', 'monitoring', 'anomaly-detection'],
    author: { username: 'srikant', displayName: 'Srikant', karma: 12450 },
    upvotes: 847,
    downvotes: 23,
    rating: 9.2,
    ratingCount: 156,
    downloads: 2340,
    comments: 67,
    createdAt: '2025-10-15T10:00:00Z',
    updatedAt: '2026-03-20T14:30:00Z',
    featured: true,
    installCommand: 'optimiser install ga4-conversion-watchdog',
    version: '2.1.0',
    compatibility: ['Claude Code', 'Dispatch'],
  },
  {
    id: 'item_2',
    slug: 'posthoz-funnel-alerter',
    title: 'PostHog Funnel Alerter',
    shortDescription: 'Tracks product funnel health and notifies teams of bottlenecks.',
    description: 'Integrates with PostHog to monitor user journey funnels, identifying where users drop off and sending proactive alerts to your team. Features heat mapping analysis, session recording links, and suggested optimization tactics.',
    type: 'agent',
    category: 'cro-growth',
    tags: ['posthog', 'funnels', 'product-analytics', 'user-journey'],
    author: { username: 'growth-hacker', displayName: 'Growth Hacker', karma: 8920 },
    upvotes: 398,
    downvotes: 15,
    rating: 8.7,
    ratingCount: 89,
    downloads: 1240,
    comments: 34,
    createdAt: '2025-11-20T09:15:00Z',
    updatedAt: '2026-02-10T16:45:00Z',
    featured: false,
    installCommand: 'optimiser install posthoz-funnel-alerter',
    version: '1.8.2',
    compatibility: ['Claude Code', 'Dispatch'],
  },
  {
    id: 'item_3',
    slug: 'email-campaign-optimizer',
    title: 'Email Campaign Optimizer',
    shortDescription: 'Analyzes email performance and suggests subject line improvements.',
    description: 'Uses AI to analyze your email campaign metrics and generates optimized subject lines based on historical performance data. Integrates with Mailchimp, Klaviyo, and SendGrid to automatically test and recommend winning variations.',
    type: 'agent',
    category: 'cro-growth',
    tags: ['email-marketing', 'optimization', 'mailchimp', 'testing'],
    author: { username: 'content-pro', displayName: 'Content Pro', karma: 6540 },
    upvotes: 176,
    downvotes: 9,
    rating: 8.4,
    ratingCount: 42,
    downloads: 567,
    comments: 18,
    createdAt: '2025-12-05T14:20:00Z',
    updatedAt: '2026-01-28T10:00:00Z',
    featured: false,
    installCommand: 'optimiser install email-campaign-optimizer',
    version: '1.5.1',
    compatibility: ['Claude Code', 'Dispatch'],
  },

  // AGENTS - DevOps & Deploy
  {
    id: 'item_4',
    slug: 'vercel-deploy-notifier',
    title: 'Vercel Deploy Notifier',
    shortDescription: 'Sends deployment status updates to your team via Slack.',
    description: 'Monitors your Vercel deployments and sends detailed status updates including build logs, performance metrics, and rollback suggestions. Features team notifications, deployment history tracking, and preview URL sharing.',
    type: 'agent',
    category: 'devops',
    tags: ['vercel', 'deployments', 'slack', 'ci-cd', 'notifications'],
    author: { username: 'devops-ninja', displayName: 'DevOps Ninja', karma: 11200 },
    upvotes: 612,
    downvotes: 18,
    rating: 9.0,
    ratingCount: 134,
    downloads: 1890,
    comments: 52,
    createdAt: '2025-09-10T08:30:00Z',
    updatedAt: '2026-03-15T11:20:00Z',
    featured: false,
    installCommand: 'optimiser install vercel-deploy-notifier',
    version: '2.3.0',
    compatibility: ['Claude Code', 'Dispatch'],
  },
  {
    id: 'item_5',
    slug: 'github-pr-reviewer',
    title: 'GitHub PR Reviewer',
    shortDescription: 'Automated code review suggestions for pull requests.',
    description: 'AI-powered code review agent that analyzes pull requests for code quality, security issues, and performance problems. Leaves detailed comments with suggestions and links to relevant documentation.',
    type: 'agent',
    category: 'devops',
    tags: ['github', 'code-review', 'automation', 'quality-assurance'],
    author: { username: 'devops-ninja', displayName: 'DevOps Ninja', karma: 11200 },
    upvotes: 341,
    downvotes: 8,
    rating: 8.8,
    ratingCount: 76,
    downloads: 945,
    comments: 28,
    createdAt: '2025-10-22T13:45:00Z',
    updatedAt: '2026-02-28T09:30:00Z',
    featured: false,
    installCommand: 'optimiser install github-pr-reviewer',
    version: '1.9.3',
    compatibility: ['Claude Code', 'Dispatch'],
  },
  {
    id: 'item_6',
    slug: 'aws-cost-watcher',
    title: 'AWS Cost Watcher',
    shortDescription: 'Tracks AWS spending and alerts on cost overruns.',
    description: 'Monitors your AWS bill in real-time, identifies cost anomalies, and suggests optimization opportunities. Generates weekly reports and integrates with Slack for instant alerts when spending exceeds budgets.',
    type: 'agent',
    category: 'devops',
    tags: ['aws', 'cost-management', 'monitoring', 'finance'],
    author: { username: 'ops-lead', displayName: 'Ops Lead', karma: 9870 },
    upvotes: 156,
    downvotes: 6,
    rating: 8.5,
    ratingCount: 38,
    downloads: 423,
    comments: 12,
    createdAt: '2025-11-30T16:10:00Z',
    updatedAt: '2026-01-15T14:25:00Z',
    featured: false,
    installCommand: 'optimiser install aws-cost-watcher',
    version: '1.4.2',
    compatibility: ['Claude Code', 'Dispatch'],
  },

  // AGENTS - Analytics & Data
  {
    id: 'item_7',
    slug: 'airtable-weekly-digest',
    title: 'Airtable Weekly Digest',
    shortDescription: 'Generates weekly summaries from your Airtable bases.',
    description: 'Automatically extracts key insights from your Airtable bases and compiles them into beautiful weekly email digests. Supports custom filtering, trend analysis, and stakeholder summaries.',
    type: 'agent',
    category: 'analytics',
    tags: ['airtable', 'reporting', 'data-analysis', 'automation'],
    author: { username: 'data-wizard', displayName: 'Data Wizard', karma: 10340 },
    upvotes: 589,
    downvotes: 31,
    rating: 8.9,
    ratingCount: 112,
    downloads: 1670,
    comments: 45,
    createdAt: '2025-10-01T11:00:00Z',
    updatedAt: '2026-03-10T15:40:00Z',
    featured: false,
    installCommand: 'optimiser install airtable-weekly-digest',
    version: '2.0.1',
    compatibility: ['Claude Code', 'Dispatch'],
  },

  // AGENTS - Product & Research
  {
    id: 'item_8',
    slug: 'slack-standup-bot',
    title: 'Slack Standup Bot',
    shortDescription: 'Collects and summarizes team standups from Slack.',
    description: 'Automatically collects standup updates from team members, generates daily summaries, and creates a searchable archive. Integrates with Linear to pull task details and progress tracking.',
    type: 'agent',
    category: 'product',
    tags: ['slack', 'team-management', 'standups', 'daily-sync'],
    author: { username: 'ops-lead', displayName: 'Ops Lead', karma: 9870 },
    upvotes: 445,
    downvotes: 12,
    rating: 8.6,
    ratingCount: 98,
    downloads: 1120,
    comments: 32,
    createdAt: '2025-11-05T09:20:00Z',
    updatedAt: '2026-02-22T13:15:00Z',
    featured: false,
    installCommand: 'optimiser install slack-standup-bot',
    version: '1.7.0',
    compatibility: ['Claude Code', 'Dispatch'],
  },
  {
    id: 'item_9',
    slug: 'linear-sprint-reporter',
    title: 'Linear Sprint Reporter',
    shortDescription: 'Generates sprint reports from Linear project data.',
    description: 'Pulls sprint metrics from Linear, creates comprehensive reports with velocity trends, burn-down charts, and individual contributor stats. Delivers automated weekly email summaries to leadership.',
    type: 'agent',
    category: 'product',
    tags: ['linear', 'sprint-planning', 'reporting', 'metrics'],
    author: { username: 'data-wizard', displayName: 'Data Wizard', karma: 10340 },
    upvotes: 234,
    downvotes: 7,
    rating: 8.3,
    ratingCount: 54,
    downloads: 678,
    comments: 19,
    createdAt: '2025-12-10T10:30:00Z',
    updatedAt: '2026-01-20T11:45:00Z',
    featured: false,
    installCommand: 'optimiser install linear-sprint-reporter',
    version: '1.3.5',
    compatibility: ['Claude Code', 'Dispatch'],
  },

  // AGENTS - Content & Copy
  {
    id: 'item_10',
    slug: 'seo-content-scheduler',
    title: 'SEO Content Scheduler',
    shortDescription: 'Plans and schedules SEO-optimized content automatically.',
    description: 'Analyzes your target keywords, generates content calendars, and schedules publishing across your blog and social channels. Includes SEO optimization suggestions and performance tracking.',
    type: 'agent',
    category: 'content',
    tags: ['seo', 'content-marketing', 'scheduling', 'organic-growth'],
    author: { username: 'content-pro', displayName: 'Content Pro', karma: 6540 },
    upvotes: 289,
    downvotes: 11,
    rating: 8.4,
    ratingCount: 65,
    downloads: 812,
    comments: 23,
    createdAt: '2025-11-12T14:00:00Z',
    updatedAt: '2026-02-18T16:30:00Z',
    featured: false,
    installCommand: 'optimiser install seo-content-scheduler',
    version: '1.6.2',
    compatibility: ['Claude Code', 'Dispatch'],
  },

  // AGENTS - Design
  {
    id: 'item_11',
    slug: 'figma-asset-exporter',
    title: 'Figma Asset Exporter',
    shortDescription: 'Exports Figma components as production-ready code.',
    description: 'Automatically converts Figma components to React, Vue, or HTML/CSS code. Maintains design system consistency and generates component documentation.',
    type: 'agent',
    category: 'design',
    tags: ['figma', 'component-generation', 'design-system', 'code-generation'],
    author: { username: 'design-craft', displayName: 'Design Craft', karma: 7650 },
    upvotes: 198,
    downvotes: 14,
    rating: 8.2,
    ratingCount: 44,
    downloads: 534,
    comments: 16,
    createdAt: '2025-12-01T12:15:00Z',
    updatedAt: '2026-01-25T10:00:00Z',
    featured: false,
    installCommand: 'optimiser install figma-asset-exporter',
    version: '1.5.0',
    compatibility: ['Claude Code', 'Dispatch'],
  },

  // AGENTS - Finance
  {
    id: 'item_12',
    slug: 'stripe-revenue-monitor',
    title: 'Stripe Revenue Monitor',
    shortDescription: 'Tracks revenue metrics and churn trends from Stripe.',
    description: 'Monitors your Stripe account for revenue patterns, subscription churn, and payment issues. Provides daily dashboards and alerts teams to declining metrics.',
    type: 'agent',
    category: 'finance',
    tags: ['stripe', 'revenue', 'churn', 'financial-metrics'],
    author: { username: 'ops-lead', displayName: 'Ops Lead', karma: 9870 },
    upvotes: 267,
    downvotes: 5,
    rating: 8.7,
    ratingCount: 58,
    downloads: 723,
    comments: 21,
    createdAt: '2025-10-28T15:45:00Z',
    updatedAt: '2026-02-05T12:30:00Z',
    featured: false,
    installCommand: 'optimiser install stripe-revenue-monitor',
    version: '1.7.1',
    compatibility: ['Claude Code', 'Dispatch'],
  },

  // SKILLS - Design & UI
  {
    id: 'item_13',
    slug: 'optimiser-pro',
    title: 'optimiser-pro',
    shortDescription: 'Premium design system toolkit with 200+ components.',
    description: 'A comprehensive design system skill that provides 200+ pre-built, customizable UI components. Includes dark mode support, accessibility features, and extensive documentation. Perfect for rapid prototyping and design consistency.',
    type: 'skill',
    category: 'design',
    tags: ['design-system', 'components', 'ui-kit', 'customizable'],
    author: { username: 'srikant', displayName: 'Srikant', karma: 12450 },
    upvotes: 1204,
    downvotes: 34,
    rating: 9.4,
    ratingCount: 287,
    downloads: 4560,
    comments: 123,
    createdAt: '2025-08-15T10:00:00Z',
    updatedAt: '2026-03-25T09:20:00Z',
    featured: true,
    installCommand: 'optimiser install optimiser-pro',
    version: '3.2.1',
    compatibility: ['Claude Code', 'Dispatch', 'Web'],
  },
  {
    id: 'item_14',
    slug: 'ui-ux-pro-max',
    title: 'ui-ux-pro-max',
    shortDescription: 'Advanced prototyping and interaction design toolkit.',
    description: 'A professional-grade design skill featuring advanced prototyping capabilities, micro-interaction patterns, and accessibility-first components. Built for designers who need production-quality outcomes.',
    type: 'skill',
    category: 'design',
    tags: ['ux-design', 'prototyping', 'interactions', 'accessibility'],
    author: { username: 'nextlevelbuilder', displayName: 'Next Level Builder', karma: 10890 },
    upvotes: 987,
    downvotes: 28,
    rating: 9.3,
    ratingCount: 213,
    downloads: 3890,
    comments: 94,
    createdAt: '2025-09-02T14:30:00Z',
    updatedAt: '2026-03-18T16:15:00Z',
    featured: true,
    installCommand: 'optimiser install ui-ux-pro-max',
    version: '2.8.5',
    compatibility: ['Claude Code', 'Dispatch', 'Web'],
  },
  {
    id: 'item_15',
    slug: 'brand-guidelines',
    title: 'brand-guidelines',
    shortDescription: 'Enforce brand consistency across all digital assets.',
    description: 'A skill for managing and enforcing brand guidelines. Includes color palette management, typography rules, imagery guidelines, and voice & tone documentation. Ensures brand consistency across all projects.',
    type: 'skill',
    category: 'design',
    tags: ['branding', 'guidelines', 'consistency', 'documentation'],
    author: { username: 'design-craft', displayName: 'Design Craft', karma: 7650 },
    upvotes: 634,
    downvotes: 16,
    rating: 9.1,
    ratingCount: 142,
    downloads: 2140,
    comments: 56,
    createdAt: '2025-10-11T11:20:00Z',
    updatedAt: '2026-02-20T13:45:00Z',
    featured: false,
    installCommand: 'optimiser install brand-guidelines',
    version: '2.1.3',
    compatibility: ['Claude Code', 'Dispatch'],
  },
  {
    id: 'item_16',
    slug: 'algorithmic-art',
    title: 'algorithmic-art',
    shortDescription: 'Generate visual art through procedural algorithms.',
    description: 'A creative skill for generating unique visual artwork using algorithmic techniques. Includes fractals, generative patterns, and AI-assisted composition tools. Perfect for designers exploring new creative possibilities.',
    type: 'skill',
    category: 'design',
    tags: ['generative-art', 'creativity', 'algorithms', 'visual-design'],
    author: { username: 'design-craft', displayName: 'Design Craft', karma: 7650 },
    upvotes: 521,
    downvotes: 22,
    rating: 8.8,
    ratingCount: 115,
    downloads: 1680,
    comments: 48,
    createdAt: '2025-11-08T09:50:00Z',
    updatedAt: '2026-02-12T14:20:00Z',
    featured: false,
    installCommand: 'optimiser install algorithmic-art',
    version: '1.9.2',
    compatibility: ['Claude Code', 'Dispatch'],
  },

  // SKILLS - DevOps & Deploy
  {
    id: 'item_17',
    slug: 'qa-engineer',
    title: 'qa-engineer',
    shortDescription: 'Comprehensive testing automation and quality assurance framework.',
    description: 'A complete QA framework skill that includes unit testing, integration testing, and end-to-end testing patterns. Features test data generation, coverage reporting, and CI/CD integration.',
    type: 'skill',
    category: 'devops',
    tags: ['testing', 'qa', 'automation', 'quality-assurance'],
    author: { username: 'devops-ninja', displayName: 'DevOps Ninja', karma: 11200 },
    upvotes: 756,
    downvotes: 19,
    rating: 9.0,
    ratingCount: 167,
    downloads: 2450,
    comments: 67,
    createdAt: '2025-09-20T13:30:00Z',
    updatedAt: '2026-03-12T10:40:00Z',
    featured: false,
    installCommand: 'optimiser install qa-engineer',
    version: '2.5.1',
    compatibility: ['Claude Code', 'Dispatch'],
  },

  // SKILLS - Analytics & Data
  {
    id: 'item_18',
    slug: 'data-pipeline-builder',
    title: 'data-pipeline-builder',
    shortDescription: 'Build and manage data pipelines with minimal code.',
    description: 'A skill for constructing robust data pipelines with ETL patterns, data transformation, and quality checks. Includes connectors for popular data sources and warehouses.',
    type: 'skill',
    category: 'analytics',
    tags: ['data-engineering', 'etl', 'pipelines', 'data-warehouse'],
    author: { username: 'data-wizard', displayName: 'Data Wizard', karma: 10340 },
    upvotes: 367,
    downvotes: 8,
    rating: 8.6,
    ratingCount: 81,
    downloads: 945,
    comments: 28,
    createdAt: '2025-12-03T10:15:00Z',
    updatedAt: '2026-01-22T15:30:00Z',
    featured: false,
    installCommand: 'optimiser install data-pipeline-builder',
    version: '1.6.0',
    compatibility: ['Claude Code', 'Dispatch'],
  },

  // SKILLS - Content & Copy
  {
    id: 'item_19',
    slug: 'doc-coauthoring',
    title: 'doc-coauthoring',
    shortDescription: 'AI-assisted document creation and collaborative writing.',
    description: 'A skill for collaborative document writing with AI suggestions, version control, and commenting features. Great for teams creating technical documentation, guides, and content.',
    type: 'skill',
    category: 'content',
    tags: ['documentation', 'writing', 'collaboration', 'content-creation'],
    author: { username: 'content-pro', displayName: 'Content Pro', karma: 6540 },
    upvotes: 489,
    downvotes: 13,
    rating: 8.5,
    ratingCount: 107,
    downloads: 1340,
    comments: 39,
    createdAt: '2025-11-15T12:45:00Z',
    updatedAt: '2026-02-08T11:20:00Z',
    featured: false,
    installCommand: 'optimiser install doc-coauthoring',
    version: '1.8.3',
    compatibility: ['Claude Code', 'Dispatch'],
  },

  // SKILLS - CRO & Growth
  {
    id: 'item_20',
    slug: 'cro-audit-framework',
    title: 'cro-audit-framework',
    shortDescription: 'Complete framework for conversion rate optimization audits.',
    description: 'A comprehensive skill for conducting CRO audits. Includes heatmap analysis, funnel optimization checklists, user behavior patterns, and A/B testing frameworks.',
    type: 'skill',
    category: 'cro-growth',
    tags: ['cro', 'optimization', 'auditing', 'conversion'],
    author: { username: 'growth-hacker', displayName: 'Growth Hacker', karma: 8920 },
    upvotes: 412,
    downvotes: 10,
    rating: 8.7,
    ratingCount: 92,
    downloads: 1120,
    comments: 34,
    createdAt: '2025-10-25T14:20:00Z',
    updatedAt: '2026-02-14T09:50:00Z',
    featured: false,
    installCommand: 'optimiser install cro-audit-framework',
    version: '1.9.0',
    compatibility: ['Claude Code', 'Dispatch'],
  },
];

export const MOCK_COLLECTIONS = [
  {
    id: 'col_1',
    slug: 'sanjow-starter-kit',
    title: 'Sanjow Ventures Starter Kit',
    description: 'Everything you need to get started with the Sanjow Ventures tech stack. This collection includes our premium design system, advanced QA framework, and top-performing growth monitoring tools.',
    curator: { username: 'srikant', displayName: 'Srikant', karma: 12450 },
    itemSlugs: ['optimiser-pro', 'ui-ux-pro-max', 'qa-engineer', 'ga4-conversion-watchdog', 'brand-guidelines'],
    itemCount: 5,
    upvotes: 234,
    rating: 9.0,
    ratingCount: 48,
    downloads: 567,
    createdAt: '2025-09-01T10:00:00Z',
    updatedAt: '2026-03-20T14:30:00Z',
  },
  {
    id: 'col_2',
    slug: 'cro-agent-stack',
    title: 'CRO Agent Stack',
    description: 'A complete stack of conversion rate optimization tools. Combines GA4 monitoring, funnel analysis, email optimization, and SEO content scheduling to maximize your conversion potential.',
    curator: { username: 'growth-hacker', displayName: 'Growth Hacker', karma: 8920 },
    itemSlugs: ['ga4-conversion-watchdog', 'posthoz-funnel-alerter', 'email-campaign-optimizer', 'seo-content-scheduler', 'cro-audit-framework'],
    itemCount: 5,
    upvotes: 189,
    rating: 8.9,
    ratingCount: 38,
    downloads: 445,
    createdAt: '2025-10-10T13:20:00Z',
    updatedAt: '2026-03-15T11:45:00Z',
  },
  {
    id: 'col_3',
    slug: 'design-intelligence-bundle',
    title: 'Design Intelligence Bundle',
    description: 'The ultimate collection for modern design teams. Includes our best-in-class design system, advanced prototyping toolkit, brand guidelines manager, and generative art tools.',
    curator: { username: 'design-craft', displayName: 'Design Craft', karma: 7650 },
    itemSlugs: ['optimiser-pro', 'ui-ux-pro-max', 'brand-guidelines', 'algorithmic-art', 'figma-asset-exporter'],
    itemCount: 5,
    upvotes: 267,
    rating: 9.1,
    ratingCount: 59,
    downloads: 678,
    createdAt: '2025-08-20T09:30:00Z',
    updatedAt: '2026-03-22T15:10:00Z',
  },
];

export const MOCK_COMMENTS = [
  {
    id: 'comment_1',
    itemSlug: 'ga4-conversion-watchdog',
    author: { username: 'growth-hacker', displayName: 'Growth Hacker', karma: 8920 },
    content: 'This has been a game-changer for our team. We caught a 15% conversion drop within minutes and were able to investigate immediately. The Slack integration is seamless.',
    createdAt: '2026-03-20T15:45:00Z',
    upvotes: 87,
    parentId: null,
  },
  {
    id: 'comment_2',
    itemSlug: 'ga4-conversion-watchdog',
    author: { username: 'data-wizard', displayName: 'Data Wizard', karma: 10340 },
    content: 'Would love to see customizable alert thresholds per traffic segment. Still 5-star though!',
    createdAt: '2026-03-18T10:20:00Z',
    upvotes: 34,
    parentId: null,
  },
  {
    id: 'comment_3',
    itemSlug: 'ga4-conversion-watchdog',
    author: { username: 'srikant', displayName: 'Srikant', karma: 12450 },
    content: 'Great suggestion! We have that on the roadmap for v2.2. Thanks for the feedback!',
    createdAt: '2026-03-18T12:00:00Z',
    upvotes: 28,
    parentId: 'comment_2',
  },
  {
    id: 'comment_4',
    itemSlug: 'optimiser-pro',
    author: { username: 'nextlevelbuilder', displayName: 'Next Level Builder', karma: 10890 },
    content: 'Absolutely stellar design system. The component variants alone save us hours on every project. Highly recommend to any design team.',
    createdAt: '2026-03-19T14:15:00Z',
    upvotes: 156,
    parentId: null,
  },
  {
    id: 'comment_5',
    itemSlug: 'optimiser-pro',
    author: { username: 'design-craft', displayName: 'Design Craft', karma: 7650 },
    content: 'Using this alongside ui-ux-pro-max and the synergy is incredible. Both work perfectly together for our entire product design pipeline.',
    createdAt: '2026-03-17T09:30:00Z',
    upvotes: 123,
    parentId: null,
  },
  {
    id: 'comment_6',
    itemSlug: 'vercel-deploy-notifier',
    author: { username: 'ops-lead', displayName: 'Ops Lead', karma: 9870 },
    content: 'Essential tool for any team using Vercel. Our incident response time has dropped significantly since we implemented this.',
    createdAt: '2026-03-16T11:00:00Z',
    upvotes: 76,
    parentId: null,
  },
  {
    id: 'comment_7',
    itemSlug: 'vercel-deploy-notifier',
    author: { username: 'devops-ninja', displayName: 'DevOps Ninja', karma: 11200 },
    content: 'Thanks for the kind words! We just added preview URL tracking in v2.3 to make deployment previews even easier to share.',
    createdAt: '2026-03-16T13:45:00Z',
    upvotes: 45,
    parentId: 'comment_6',
  },
  {
    id: 'comment_8',
    itemSlug: 'ui-ux-pro-max',
    author: { username: 'srikant', displayName: 'Srikant', karma: 12450 },
    content: 'The micro-interaction library alone is worth the price. Quality and attention to detail are unmatched.',
    createdAt: '2026-03-15T16:20:00Z',
    upvotes: 98,
    parentId: null,
  },
];

export const TRENDING_TAGS = [
  'claude-code',
  'automation',
  'ga4',
  'vercel',
  'slack',
  'monitoring',
  'cro',
  'design-system',
  'testing',
  'ai-agents',
];

export const STATS = {
  agents: 47,
  skills: 83,
  totalVotes: 24680,
  contributors: 312,
};
